project_id = "ucziztbaamtmmvycfyuz"

[functions.ai-question-generator]
verify_jwt = true

[functions.generate-mcqs]
verify_jwt = true

[functions.generate-exam]
verify_jwt = true

[functions.evaluate-subjective]
verify_jwt = true

[functions.generate-diagram-question]
verify_jwt = true
