import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FileText, Download, Printer } from "lucide-react";
import { toast } from "sonner";

interface SheetConfig {
  title: string;
  subtitle: string;
  questions: number;
  options: number;
  studentInfo: boolean;
}

export const AnswerSheetGenerator = () => {
  const [config, setConfig] = useState<SheetConfig>({
    title: "OMR ANSWER SHEET",
    subtitle: "Questions: 10 | Options: 4 | Columns: 1",
    questions: 10,
    options: 4,
    studentInfo: true
  });

  const generateSVG = (): string => {
    const width = 595; // A4 width in points
    const height = 842; // A4 height in points
    
    // Layout parameters - fixed positioning
    const titleAreaHeight = 120;
    const studentInfoHeight = config.studentInfo ? 80 : 0;
    const instructionsHeight = 80;
    const questionsStartY = titleAreaHeight + studentInfoHeight + instructionsHeight + 20;
    const questionAreaHeight = height - questionsStartY - 40;
    const questionHeight = questionAreaHeight / config.questions;
    const leftMargin = width * 0.08;
    const bubbleAreaWidth = width * 0.6;
    const bubbleSpacing = bubbleAreaWidth / config.options;
    
    const bubbleRadius = Math.min(questionHeight * 0.15, bubbleSpacing * 0.15);
    
    let svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
  <rect width="100%" height="100%" fill="white"/>
  
  <!-- Header -->
  <text x="${width/2}" y="60" text-anchor="middle" font-family="Arial, sans-serif" font-size="24" font-weight="bold">${config.title}</text>
  <text x="${width/2}" y="85" text-anchor="middle" font-family="Arial, sans-serif" font-size="12" fill="#666">${config.subtitle}</text>`;

    // Student information section
    if (config.studentInfo) {
      svg += `
  <!-- Student Info -->
  <text x="50" y="140" font-family="Arial, sans-serif" font-size="12" font-weight="bold">Name:</text>
  <line x1="90" y1="140" x2="300" y2="140" stroke="black" stroke-width="1"/>
  
  <text x="350" y="140" font-family="Arial, sans-serif" font-size="12" font-weight="bold">Date:</text>
  <line x1="380" y1="140" x2="545" y2="140" stroke="black" stroke-width="1"/>
  
  <text x="50" y="170" font-family="Arial, sans-serif" font-size="12" font-weight="bold">ID:</text>
  <line x1="75" y1="170" x2="300" y2="170" stroke="black" stroke-width="1"/>
  
  <text x="350" y="170" font-family="Arial, sans-serif" font-size="12" font-weight="bold">Class:</text>
  <line x1="385" y1="170" x2="545" y2="170" stroke="black" stroke-width="1"/>`;
    }

    // Instructions
    svg += `
  <!-- Instructions -->
  <rect x="40" y="190" width="${width-80}" height="80" fill="#f8f9fa" stroke="#dee2e6" stroke-width="1" rx="5"/>
  <text x="60" y="210" font-family="Arial, sans-serif" font-size="14" font-weight="bold">INSTRUCTIONS:</text>
  <text x="60" y="230" font-family="Arial, sans-serif" font-size="10" fill="#666">• Use a dark pen or pencil to completely fill the circles</text>
  <text x="60" y="245" font-family="Arial, sans-serif" font-size="10" fill="#666">• Make dark marks that completely fill the circle</text>
  <text x="60" y="260" font-family="Arial, sans-serif" font-size="10" fill="#666">• Erase cleanly any marks you wish to change</text>`;

    // Questions and bubbles
    const options = ['A', 'B', 'C', 'D'];
    
    for (let question = 1; question <= config.questions; question++) {
      const questionCenterY = questionsStartY + (question - 0.5) * questionHeight;
      
      // Question number
      svg += `
  <text x="30" y="${questionCenterY + 5}" font-family="Arial, sans-serif" font-size="12" font-weight="bold">${question}.</text>`;
      
      // Option bubbles
      for (let optionIndex = 0; optionIndex < config.options; optionIndex++) {
        const bubbleCenterX = leftMargin + (optionIndex + 0.5) * bubbleSpacing;
        const option = options[optionIndex];
        
        // Bubble circle
        svg += `
  <circle cx="${bubbleCenterX}" cy="${questionCenterY}" r="${bubbleRadius}" fill="white" stroke="black" stroke-width="2"/>`;
        
        // Option label
        svg += `
  <text x="${bubbleCenterX}" y="${questionCenterY - bubbleRadius - 10}" text-anchor="middle" font-family="Arial, sans-serif" font-size="10" font-weight="bold">${option}</text>`;
      }
    }

    // Footer
    svg += `
  <text x="${width/2}" y="${height - 20}" text-anchor="middle" font-family="Arial, sans-serif" font-size="8" fill="#999">Generated by OMR Scanner | Configuration: ${config.questions}Q × ${config.options}O × 1C</text>
</svg>`;

    return svg;
  };

  const downloadSheet = () => {
    const svg = generateSVG();
    const blob = new Blob([svg], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `answer-sheet-${config.questions}q-${config.options}o.svg`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Answer sheet downloaded successfully!");
  };

  const printSheet = () => {
    const svg = generateSVG();
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>OMR Answer Sheet</title>
          <style>
            body { margin: 0; padding: 20px; }
            svg { max-width: 100%; height: auto; }
            @media print {
              body { margin: 0; padding: 0; }
              svg { width: 100%; height: 100%; }
            }
          </style>
        </head>
        <body>
          ${svg}
        </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            Answer Sheet Generator
          </CardTitle>
          <CardDescription>
            Generate OMR answer sheets optimized for the bubble detection system
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label htmlFor="title">Sheet Title</Label>
              <Input
                id="title"
                value={config.title}
                onChange={(e) => setConfig(prev => ({ ...prev, title: e.target.value }))}
                placeholder="OMR ANSWER SHEET"
              />
            </div>
            
            <div>
              <Label htmlFor="subtitle">Subtitle</Label>
              <Input
                id="subtitle"
                value={config.subtitle}
                onChange={(e) => setConfig(prev => ({ ...prev, subtitle: e.target.value }))}
                placeholder="Math Quiz - Class 10A"
              />
            </div>
            
            <div>
              <Label htmlFor="questions">Number of Questions</Label>
              <Select 
                value={config.questions.toString()} 
                onValueChange={(value) => setConfig(prev => ({ 
                  ...prev, 
                  questions: parseInt(value),
                  subtitle: `Questions: ${value} | Options: ${prev.options} | Columns: 1`
                }))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="5">5 Questions</SelectItem>
                  <SelectItem value="10">10 Questions</SelectItem>
                  <SelectItem value="15">15 Questions</SelectItem>
                  <SelectItem value="20">20 Questions</SelectItem>
                  <SelectItem value="25">25 Questions</SelectItem>
                  <SelectItem value="30">30 Questions</SelectItem>
                </SelectContent>
              </Select>
            </div>
            
            <div>
              <Label htmlFor="options">Options per Question</Label>
              <Select 
                value={config.options.toString()} 
                onValueChange={(value) => setConfig(prev => ({ 
                  ...prev, 
                  options: parseInt(value),
                  subtitle: `Questions: ${prev.questions} | Options: ${value} | Columns: 1`
                }))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="3">3 Options (A, B, C)</SelectItem>
                  <SelectItem value="4">4 Options (A, B, C, D)</SelectItem>
                  <SelectItem value="5">5 Options (A, B, C, D, E)</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <input
              type="checkbox"
              id="studentInfo"
              checked={config.studentInfo}
              onChange={(e) => setConfig(prev => ({ ...prev, studentInfo: e.target.checked }))}
              className="rounded"
            />
            <Label htmlFor="studentInfo">Include student information fields</Label>
          </div>

          <div className="flex gap-2">
            <Button onClick={downloadSheet} className="flex-1">
              <Download className="w-4 h-4 mr-2" />
              Download SVG
            </Button>
            <Button onClick={printSheet} variant="outline" className="flex-1">
              <Printer className="w-4 h-4 mr-2" />
              Print Sheet
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Preview */}
      <Card>
        <CardHeader>
          <CardTitle>Preview</CardTitle>
          <CardDescription>
            This sheet is optimized for 100% detection accuracy
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div 
            className="border rounded-lg p-4 bg-white max-w-full overflow-auto"
            dangerouslySetInnerHTML={{ __html: generateSVG() }}
          />
        </CardContent>
      </Card>
    </div>
  );
};